name: YAML validation

on:
  push:
    branches: [ develop, feat/yaml-workflow ]
  pull_request:
    branches: [ master, develop ]

jobs:
  yaml-validation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: YAML Lint
      uses: ibiqlik/action-yamllint@v1.0.0
      with:
        ## File(s) or Directory, separate by space if multiple files or folder are specified
        file_or_dir: modelFiles/
        ## Path to custom configuration
        # config_file: # optional
        ## Custom configuration (as YAML source)
        config_data: "{extends: default, rules: {line-length: disable}}"
        ## Format for parsing output [parsable,standard,colored,auto]
        # format: # optional, default is colored
        ## Return non-zero exit code on warnings as well as errors
        # strict: # optional, default is false